### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by jobayer977** [jamesgeorge007/csstox#47]
![image](https://github.com/user-attachments/assets/201ecd41-54af-41d2-a9bb-b184f03e25e2)

**Comment by brianangulo** [comment]
@jamesgeorge007 thank you so much for this project. I use this all the time. Maybe you could deploy it via Github Pages for reliability?

**Comment by brianangulo** [comment]
This is actually solved @jobayer977
